### ISSUE TITLE
Library not loading

### ISSUE THREAD

**Issue by mehlkopf** [HappenApps/Quiver-iOS#11]
Hi,

unfortunately, I am not able to load my (or as I've tested it, any) library over my WebDAV server. It's connecting correctly and showing me the library, such that I can choose it, but it just opens an empty library without any notes and notebooks. This does not change when synchronizing manually by pull to refresh.
The issue is not related to my library, as I've tested it with a completely newly created, 1-note library. I'm using a Seafile server (https://url.de:8001/seafdav/folder, username is a mail address) ...
Thanks!

Best,
Andreas

**Comment by ylian** [comment]
Can you send me a test account for the server? Thanks.

**Comment by mehlkopf** [comment]
I've sent you an e-mail with the account informations - thank you! :)

**Comment by ylian** [comment]
Fixed in Build 6. Just pushed out.
