### ISSUE TITLE
Swift syntax styling not complete

### ISSUE THREAD

**Issue by trozware** [HappenApps/Quiver-iOS#14]
Other languages that I have checked look OK, but Swift does not render the same as it does on the desktop app.

**Comment by ylian** [comment]
It's because I have updated the Swift syntax highlighter. Is it actually worse than the previous one? Then I would need to revert it back.

**Comment by trozware** [comment]
The 2 attached files show exactly the same cells formatted in Quiver for Mac and Quiver for iPad both using the Solarized Light theme.
There are a lot fewer colored tokens in the iPad version. Checking in Xcode, I see that it is different to both but that is the goal I think you should be aiming for.

Mac:
<img width="886" alt="mac" src="https://cloud.githubusercontent.com/assets/5117298/13862456/2387b654-ecdf-11e5-88fd-c8158822b217.png">

iPad:
![ipad](https://cloud.githubusercontent.com/assets/5117298/13862461/2c33b636-ecdf-11e5-9cd8-91148c4d445a.png)

**Comment by ylian** [comment]
Thanks. I will revert it back.

**Comment by ylian** [comment]
Actually I was able to merge the two. Please try this beta build (3.0.2 Build 85): https://dl.dropboxusercontent.com/u/3445731/Quiver%203.0.2%20Build%2085.zip

**Comment by trozware** [comment]
I like this version a lot :-)


Here is the same script shown in the beta.

**Comment by ylian** [comment]
Fixed in Build 7.
