### ISSUE TITLE
Dropbox not syncing

### ISSUE THREAD

**Issue by bnmnetp** [HappenApps/Quiver-iOS#15]
The only way I can get changes I make in my notes (or new notes) to show up on my iPad is to go to settings on the iPad and use Open an Existing Library.  Then I can tap on the cloud icon next to the notebook name and it will re-download the notebook with all changes.  

I thought syncing with dropbox was supposed to work in this first beta?

Thanks.

**Comment by ylian** [comment]
You should be able to go into a notebook, pull down to refresh.

**Comment by bnmnetp** [comment]
Thats what I thought.  And when I just tried again now, It did sync...  I think that earlier I may have pulled down back in the navigation pane and although I got the spinner that made me think it might be syncing nothing did happen.  Pulling down while in the notebook does seem to sync both new notes as well as old notes with changes.

Thanks.

**Comment by ylian** [comment]
Thanks. That's expected. Pulling down the notebook list doesn't do anything at the moment. I will implement that shortly.

**Comment by bnmnetp** [comment]
One thing that I did note is that when I pull down inside a notebook to refresh If I have a note that changed selected, I do not see the changes in the note until I select a different note and then go back to the note that changed.

**Comment by ylian** [comment]
Yep, will fix shortly.

**Comment by ylian** [comment]
Merged the remaining issue with #32.
