### ISSUE TITLE
Settings > Default Note Order doesn't change order

### ISSUE THREAD

**Issue by denis** [HappenApps/Quiver-iOS#18]
`Settings` > `Default Note Order` doesn't change note order. Notes are always ordered by title.

**Comment by Euqah** [comment]
I'm having this issue as well. Has there been any update to this? I just posted an issue on this before I realized you posted it already. :)

**Comment by Euqah** [comment]
I also wanted to ask on whether there is a way to sort notebooks as well instead of just notes.

**Comment by ylian** [comment]
Coming soon.

**Comment by ylian** [comment]
Fixed in Build 7.
