### ISSUE TITLE
Can't open .qvnotebook file from WebDAV

### ISSUE THREAD

**Issue by helli72** [HappenApps/Quiver-iOS#19]
Hi,

just installed the very recent update (some minutes ago) and tried again to open a .qvnotebook file. But it doesn't work

I tried following:
1) insert the complete url+path+filename into the WebDAV setting -> I see the content of the .qvnotebook file in the WebDAV file browser, but nothing is imported
2) insert only the url+path -> I see the .qvnotebook file, but filename isn't selectable
3) insert only the url, browse to the path and see the .qvnotebook file, but filename isn't selectable

Maybe I'm doing something wrong!? How is your way to use WebDAV? Thanks!

Btw, folder and filenames in my WebDAV server is now ok.

**Comment by ylian** [comment]
You should open your Quiver.qvlibrary file, not the notebook.

**Comment by ylian** [comment]
Also, in the settings, just enter the url, browse to the path, and select Quiver.qvlibrary.

**Comment by helli72** [comment]
Ok, got it. It works. Thanks!
