### ISSUE TITLE
Change default sort order

### ISSUE THREAD

**Issue by akaman** [HappenApps/Quiver-iOS#24]
I would suggest having the default sort order to be the last edited at the top of the list.

**Comment by Euqah** [comment]
I added in an issue where I thought adding an option to manually drag around notes would be helpful. I think your issue got added into the app since I'm seeing it as an option for "Date Updated" ascending and descending. :)

**Comment by ylian** [comment]
Fixed in Build 7. Now the default sort order (updated date, descending) is honored.
