### ISSUE TITLE
Some text that's been imported in is showing up faded or very light grey over white. 

### ISSUE THREAD

**Issue by Euqah** [HappenApps/Quiver-iOS#31]
![img_0179](https://cloud.githubusercontent.com/assets/16074466/13902077/ee0b95ac-ee07-11e5-9bc8-1e1097cc24ef.PNG)

**Comment by Euqah** [comment]
I'm unable to change the font color or adjust anything through the iOS app but everything shows up fine on the OSX application.

**Comment by ylian** [comment]
Send me the note please.

**Comment by Euqah** [comment]
![img_0180](https://cloud.githubusercontent.com/assets/16074466/13902092/c8c8daec-ee08-11e5-933a-190460e4b4ec.PNG)

**Comment by Euqah** [comment]
My iPad's currently charging but I'll upload the file here as soon as it's back up,

**Comment by ylian** [comment]
Oh you can only send me the note file from the Mac app. On the Mac app, right click on the note, choose "Show in Finder", and send me the ".qvnote" file. You may need to zip it before emailing it to me. Thanks.

**Comment by Euqah** [comment]
OH. I was wondering about that since I went to export the note and none of the export options were working. The pictures are from my iPad.

**Comment by ylian** [comment]
Yeah, the pictures are from iPad, but I assume the note was created on the Mac?

**Comment by Euqah** [comment]
Yes, it was. Would you like me to just email to you? I'm trying to upload it here but GitHub is saying that it isn't supported.

**Comment by ylian** [comment]
Yeah, please email to me.

**Comment by Euqah** [comment]
Sent. Hopefully I did that right!

**Comment by Euqah** [comment]
I sent the first file but not the second. I figure that if the issue is on one, it'll be the same across any others. I can email the second file if you need it.

**Comment by Euqah** [comment]
Issue was caused by pasting from a website and not clearing the original formatting. A dark theme caused it to go unnoticed. Clear the formatting to fix the issue.
