### ISSUE TITLE
Unable to Load the WebDAV

### ISSUE THREAD

**Issue by Contextualist** [HappenApps/Quiver-iOS#4]
After I filled the server and account info and click open the WebDAV, it just comes an empty directory: I can't even see the root directory. 
I use NutStore for my WebDAV, and I have made sure the accessibility with another WebDAV navigator app.

**Comment by ylian** [comment]
Could you provide me a test account for your WebDAV server?

**Comment by Contextualist** [comment]
Yes, I've just sent a test account to your Gmail.

**Comment by ylian** [comment]
Got it. Thanks!

**Comment by ylian** [comment]
Just pushed out a new build (6). Try it and it should work.
