### ISSUE TITLE
Unable to sign up for beta

### ISSUE THREAD

**Issue by cassidyclawson** [HappenApps/Quiver-iOS#41]
Hello!

Big fan and desktop customer here. I'm interested in running the beta on my iPhone and new iPad Pro.

The old beta sign up URL (http://eepurl.com/bItzIv) appears to be dead.

Is there a new way to submit my info for inclusion in TestFlight?

Thanks and keep up the great work!

**Comment by ylian** [comment]
The beta sign up URL is working. Or you can just send me an email at ylian@happenapps.com.
