### ISSUE TITLE
[Feature Request] Possible Web App in the future?

### ISSUE THREAD

**Issue by Euqah** [HappenApps/Quiver-iOS#46]
That way Quiver could be multi-plat instead of being limited to iOS or OSX. :) Just an idea.

**Comment by ylian** [comment]
Yep, I'm looking into Electron.

**Comment by Euqah** [comment]
Any progress on this? :)

**Comment by helli72** [comment]
Any progress or especially with the iOS app? As time goes by and don't know which is the 'final' note solution for me, I found http://leanote.org
