### ISSUE TITLE
Google Drive is completely blank

### ISSUE THREAD

**Issue by ajorgensen** [HappenApps/Quiver-iOS#48]
I cannot seem to get Google Drive integration to work. Whenever I login and allow connection its completely blank and I cannot select my quiver library folder. Dropbox seems to work fine however.

![img_1123](https://cloud.githubusercontent.com/assets/509779/16383277/782f9498-3c52-11e6-8062-c3110e5880fb.PNG)
![img_1122](https://cloud.githubusercontent.com/assets/509779/16383278/78325688-3c52-11e6-9829-96bdc503c164.PNG)

Anything I can do to help diagnose? Testflight says I am on version 1.0 (7)

**Comment by kevindavenport** [comment]
What are you trying to do? I thought Google wasn't an option in the iOS app.

**Comment by ajorgensen** [comment]
It was at one point. I dont use this app anymore so I'll go ahead and close it.
