### ISSUE TITLE
Unable to open from Google Drive

### ISSUE THREAD

**Issue by ghzio** [HappenApps/Quiver-iOS#5]
I stored a library from the desktop app in Google Drive. After connecting to the Google Drive from the iOS app I can go to the folder but can neither select the library bundle to be opened nor can go into this folder. The name is greyed out.

The library is the only file in this folder in Google Drive. It has only two entries, so possible usage limits from Google's side should not be limiting.

After a while (trigger unknown), when trying to open the library again from the settings menu Google Drive came up completely empty and I had to reconnect Google Drive before even able to see files and folders again

**Comment by ylian** [comment]
Can you take a screenshot of the folder with the library bundle greyed out?

**Comment by ghzio** [comment]
Attached are two screenshots. One is showing the inaccessible Quiver bundle in Google Drive.

The other one shows another related observation. Google Drive "forgets" to have been authorized or comes up empty for some other reason. This makes me end up with multiple Google Drives. See the other screen shot.

I had both cases: Google Drive showing empty and Google Drive not being connected anymore at all and Quiver asking to connect to Drive again at start.

![datei_000](https://cloud.githubusercontent.com/assets/10948571/13710570/8cee0af0-e7ba-11e5-8e19-21fdf7d5b329.png)
![datei_001](https://cloud.githubusercontent.com/assets/10948571/13710571/8cf00ed6-e7ba-11e5-9fea-65730a58fafb.png)

**Comment by ylian** [comment]
Okay. First, right now you can only open a Quiver library file (Quiver.qvlibrary). I haven't got around to shared notebooks yet. So move your notebooks to Google Drive, then open it from the iOS device.

Second, yes, Google Drive authentication expires after an hour. But I added a token refresh when you refresh a notebook's notes.

**Comment by ghzio** [comment]
I have moved the library to the Google Drive folder. Works as expected.
