### ISSUE TITLE
Is there exactly date for release?

### ISSUE THREAD

**Issue by DevTalking** [HappenApps/Quiver-iOS#50]

**Comment by vvxo** [comment]
likewise! I've been waiting

**Comment by pralayb007** [comment]
Ditto! :(

**Comment by kingdaa** [comment]
re

**Comment by rdesanno** [comment]
Yeah, looking forward to try this out

**Comment by mszykora** [comment]
I've been waiting

**Comment by Nemesisprime** [comment]
Ditto here 👍

**Comment by rytonbay** [comment]
Love Quiver. Can't wait.

**Comment by misteryiz** [comment]
Waiting ...  Hope to see some kind of ETA here.

**Comment by lnikj** [comment]
Pretty please :)

**Comment by LukeDefeo** [comment]
Cant wait for the iOS release then i can ditch evernote :)

**Comment by shure22** [comment]
Likewise, being desperately waiting for it!!

**Comment by Johnny5k** [comment]
+1 Evernote's killing me when it comes to code notes.

**Comment by ryanchou1991** [comment]
Waitting for so long ? any exactly date for releasing?

**Comment by iamaleaf** [comment]
Any updates on this would be so welcome, I really need to be able to at least view my notes on iOS as I use them  to study for uni and would love to have access on the go, on long train rides, etc.

**Comment by mszykora** [comment]
I've been waiting

**Comment by ylian** [comment]
A read-only version will be released this month. It will support Dropbox, iCloud and WebDAV syncing. And it will be free.

**Comment by Nemesisprime** [comment]
I just cheered out loud! Can't wait and glad to hear from you again!

**Comment by ylian** [comment]
@Nemesisprime Yep, it's important to release something that people can use, even if it's limited. I have most features (for read-only version) already working in the TestFlight beta, and will trim some unimplemented features and improve syncing reliability.

**Comment by LukeDefeo** [comment]
Why don't you charge a bit of money, id rather pay for it to support development of it. My biggest concern with quiver is that it is a one many show, and if you burn out, get board, die etc then my notes are going to stagnate.

**Comment by ylian** [comment]
@LukeDefeo I can't charge for a read-only version in good conscience. No need to worry about those eventualities. The data format is open, there are many export options, and I am doing fine.

**Comment by JohnKacz** [comment]
Can you add a in-app purchase for $0.99 as a thank you? Or would that take too much effort to be worth it?

**Comment by ylian** [comment]
@JohnKacz I will leave the option open for future versions when full editing functionality is implemented.

**Comment by Menq** [comment]
Will it on the Chinese App Store ? 
Thanks for all the work you gays done

**Comment by thekoc** [comment]
@Menq 
Did you mean "guys"....

**Comment by shure22** [comment]
Any updated information about the release of read-only version?
I've been refreshing my app store several times these days. It seems like it isn't going as scheduled.

**Comment by ylian** [comment]
@shure22  Yep, it's a bit later than scheduled, but it's quite close. Should be this week.

**Comment by garion9013** [comment]
Yay! So close to release!

**Comment by mayoralito** [comment]
Hi guys, @ylian 
Do you have a thread that I/we can follow so I/we can get updates from coming release? 
Thanks for all the hard work. 👍

**Comment by ylian** [comment]
Quiver for iOS is here. As mentioned, it's read-only, but free to download.

https://itunes.apple.com/app/quiver-take-better-notes/id977882194?mt=8
