### ISSUE TITLE
Testflight period has ended. Any updates coming?

### ISSUE THREAD

**Issue by lifeisbebop** [HappenApps/Quiver-iOS#52]
The most recent beta has stopped functioning. Even without write/edit capability I've been relying on the beta to access and read my notes on my iPad. Is there any clear roadmap for Quiver-iOS? It is completely understandable that your priorities can change from when you started working on this but some level of clarity regarding your plans seems to be in order.

**Comment by ylian** [comment]
Thanks for your understanding. I just renewed the beta build.

Things are much better for me now, and I have been working through the holidays on an update to the Mac version (mostly performance improvements). Will push out the Mac update this weekend, then resume the iOS development.

**Comment by mayoralito** [comment]
Hi @ylian Is there any way that I get an invite or collaborate with the iOS app?

**Comment by mattdavenport** [comment]
2nd that. I would love an invite for testing/PRs for the iOS app.

**Comment by mayoralito** [comment]
hey @mattdavenport they released the app a few days ago - https://github.com/HappenApps/Quiver-iOS/issues/50#issuecomment-309609708
