### ISSUE TITLE
Picture not showing on iOS client

### ISSUE THREAD

**Issue by liweijian** [HappenApps/Quiver-iOS#56]
Quiver for iOS is great!

I'm using Dropbox to store the data, but I found that some picture would be shown.

![noshow](https://user-images.githubusercontent.com/19320783/27415397-69bbbe66-5739-11e7-9bd9-a1ab5079740d.jpeg)

But it seems that the picutre was on my dropbox:

```bash
$ grep "1345.png" content.json
...目标重量是 10 时，对应的图如下，其中粉色圈的超重，需要丢弃，浅蓝色方的是答案。\n![1345.png](quiver-image-url/5ECC916BC282A03041CEE96600B62DEA.png)\n\n核心算法\n...

$ ls resources/5ECC916BC282A03041CEE96600B62DEA.png
resources/5ECC916BC282A03041CEE96600B62DEA.png

$ pwd
/Users/liweijian/Dropbox/Quiver.qvlibrary/61973C81-312A-4C6B-9A8B-3C77A2C52753.qvnotebook/32F1420B-8E5D-4323-B0CE-916B9D6BF9BA.qvnote
```

**Comment by ylian** [comment]
Only missing this picture or all pictures? Also try "pull down to refresh" in the notebook.

**Comment by liweijian** [comment]
"pull down to refresh" works!
