### ISSUE TITLE
Will Quiver-iOS support iCloud in the future?

### ISSUE THREAD

**Issue by liweijian** [HappenApps/Quiver-iOS#6]
Both Dropbox and Google drive are nightmares for our guys in China.

I've tried to share the `Quiver.qvlibrary` iCloud drive to Quiver on my iPad air 2, it can't load this folder.

I tried to use Dropbox, after typing my username and password in the setting menu, I couldn't click the `allowed` button show by Dropbox.

I tried to use Google Drive, but it seems most of my notes lost in iPad.

**Comment by ylian** [comment]
Yes, iCloud Drive will be supported soon.

The Dropbox login issue is resolved. Please try again.

**Comment by jersearls** [comment]
Ping. Please add icloud :(

**Comment by Sidetalker** [comment]
Is quiver dead?

**Comment by jersearls** [comment]
hope not, just started using it!

**Comment by matchavez** [comment]
It’s good software, but the author does this in his spare time apparently. Personally, I’ve given up and just switched to Typora/Atom, and Dropbox. 

Markdown code fencing works in place of cells, and I can then use 1Writer as my phone app. It’s what Quiver should have been, but in reality, will never be if the situation doesn’t change. 

I could be wrong, but the author tends to occasionally respond to critical stuff here, but iOS is dead/read-only and fixes here feel like maintenance for the purpose of not getting trashed on the App Store. 

Such potential wasted, thus far.

**Comment by matchavez** [comment]
*and iOS. Ugh.

**Comment by jersearls** [comment]
Bummer, I'm incredibly impressed with how polished the macOS app is. iOS support isn't a dealbreaker for me, I have apple notes for the notes I'd take on mobile anyway, but it would be a nice addition.

**Comment by Sidetalker** [comment]
I would totally contribute to full featured iOS (and iCloud syncing on the macOS side as needed). I love quiver as well and still use it because it’s awesome.
