### ISSUE TITLE
Quiver 3.2 is out... will there be an iOS two-way sync?

### ISSUE THREAD

**Issue by matchavez** [HappenApps/Quiver-iOS#65]
Is there any reason to think that this will be available? Is this on the roadmap, or is this dropped?

**Comment by ylian** [comment]
iOS two-way sync is a big effort. It won't happen before editor rewrite (planned for Quiver 3.3). Without a proper editor that works on mobile devices, two-way sync won't make sense.

**Comment by matchavez** [comment]
OK, so it won't work with 3.2 - that's good to know.

So 3.3 will be two-way?

Also, remember when I offered the idea where you could just open .md files in Quiver... that would work enough... you could then depend on third party editors... ?

Looking forward to the ecosystem all working. :)

**Comment by ylian** [comment]
Regarding the file format, I have made the decision not to support opening Markdown directly. Quiver is designed for note-taking, not a Markdown editor. The current .qvnote file format is a better fit for Quiver's usecase.

Quiver for iOS 1.1 is coming up next with more syncing options. But two-way syncing with full editing is going to take a while to happen.

**Comment by matchavez** [comment]
https://www.raywenderlich.com/5960-text-kit-tutorial-getting-started

**Comment by matsieftw** [comment]
>Regarding the file format, I have made the decision not to support opening Markdown directly. Quiver is designed for note-taking, not a Markdown editor. The current .qvnote file format is a better fit for Quiver's usecase.

If that's the case can you make a Quiver flavored markdown that does outlining/numbered lists better?

**Comment by matchavez** [comment]
Also, I mean this with all sincerity. Agenda 4.0 should be an iOS app, full stop. It should be a run-able app in 10.15, under their crossover/emulator. My suggestion is based on the fact it's going to take you a while to do this anyhow, but if you go all iOS, you'll avoid sync issues. It is the future...

Good luck. I'll check back in a few months. :)
